apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: romanysefen/query-ms
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: query-ms
spec:
  selector:
    app: query
  ports:
    - port: 5002
      targetPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: query-svc
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - port: 5002
      targetPort: 5002
