apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: eventbus
          image: romanysefen/eventbus-ms:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
